### ISSUE TITLE
Attention.set_processor() got an unexpected keyword argument '_remove_lora'

### ISSUE THREAD

**Issue by deepfree2023** [TemryL/ComfyUI-IDM-VTON#18]
Hi, anyone encounted this error too? 

2024-05-08 13:24:55,102- root:179- ERROR- !!! Exception during processing!!! Attention.set_processor() got an unexpected keyword argument '_remove_lora'
2024-05-08 13:24:55,108- root:180- ERROR- Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\nodes\pipeline_loader.py", line 53, in load_pipeline
    unet = UNet2DConditionModel.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 650, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 259, in from_config
    model = cls(**init_dict)
            ^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 653, in inner_init
    init(self, *args, **init_kwargs)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 791, in __init__
    self.set_attn_processor(attn_procs)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 852, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor, _remove_lora=_remove_lora)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 849, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor, _remove_lora=_remove_lora)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 849, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor, _remove_lora=_remove_lora)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 849, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor, _remove_lora=_remove_lora)
  [Previous line repeated 3 more times]
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\unet_hacked_tryon.py", line 846, in fn_recursive_attn_processor
    module.set_processor(processor.pop(f"{name}.processor"), _remove_lora=_remove_lora)
TypeError: Attention.set_processor() got an unexpected keyword argument '_remove_lora'

**Comment by dicarne** [comment]
same error

**Comment by lldacing** [comment]
me too

**Comment by lldacing** [comment]
I used diffusers==0.27.2 before and modified the source code in order to solve the import failed error. 
I reinstalled diffusers==0.25.1, it works.
