### ISSUE TITLE
Exception during processing!!! unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Danny-zhang-xu** [TemryL/ComfyUI-IDM-VTON#65]
Exception during processing!!! unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\nodes\idm_vton.py", line 100, in make_inference
    images = pipeline(
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\tryon_pipeline.py", line 1693, in __call__
    add_time_ids, add_neg_time_ids = self._get_add_time_ids(
  File "C:\BaiduNetdiskDownload\zx\hnzfzxhz\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\idm_vton\tryon_pipeline.py", line 1044, in _get_add_time_ids
    self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim

**Comment by Danny-zhang-xu** [comment]
Please which master to help solve!

**Comment by Danny-zhang-xu** [comment]
好多BUG,First of all, thank the author for your efforts! If only can make a little more stable version out of the better! How to have the deployment file!

**Comment by Danny-zhang-xu** [comment]
好多BUG,First of all, thank the author for your efforts! If only can make a little more stable version out of the better! How to have the deployment file!
[Uploading 报错.txt…]()
